apiVersion: v1
kind: Service
metadata:
  name: shopping-list-service
spec:
  selector:
    app: MyShoppingList
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 5000
  type: LoadBalancer
